# SPDX-License-Identifier: GPL-3.0-only
# Original at https://github.com/tyron12233/CodeAssist/blob/main/.github/workflows/build-apk.yml
# Changes: Minor adjustments, removal of Cancel previous runs step, but every change can be found with a simple diff.

name: Android CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build debug APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Build debug APK with AAB support
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: assembleWithAabOutputSupportDebug
          distributions-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true

      - name: Upload debug APK with AAB support
        uses: actions/upload-artifact@v2
        with:
          name: apk-withAabOutputSupport-debug
          path: app/build/outputs/apk/withAabOutputSupport/debug

      - name: Build debug APK without AAB support
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: assembleWithoutAabOutputSupportDebug
          distributions-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true

      - name: Upload debug APK without AAB support
        uses: actions/upload-artifact@v2
        with:
          name: apk-withoutAabOutputSupport-debug
          path: app/build/outputs/apk/withoutAabOutputSupport/debug
